import Link from 'next/link'
import '../globals.css'
import { getPages } from '@/sanity/sanity-utils'

export const metadata = {
  title: 'My Awesome Site!',
  description: 'Generated by create Next + sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages()

  return (
    <html lang="en">

      <body className=" bg-white text-black dark:bg-black dark:text-white max-w-3xl mx-auto py-10 px-6">

        <header className=' flex items-center justify-between'>
          <Link href="/" className='bg-gradient-to-r hover:bg-gradient-to-l from-orange-400 via-red-500 to-blue-600  bg-clip-text text-transparent transition duration-250 ease-out font-bold text-lg pl-2' >Javed</Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline font-bold ">{page.title}</Link>
            ))}

          </div>
        </header>

        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
